# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17a9d00f1fe438dc01a2884cdaedc3cd50b8e40b8d5c13aab4bced3f04a158e13ea3cfe3f5a60fcf2c939969e3ab80c6a6a605b8bb23312b1b044e594f469e7a

test:
  secret_key_base: 99497563dfe024553d94739d0725ebc689b959255cac9ed3696e8c235e4a4924a9f5220fe2220282452b240c6587ae6e4168c93580e278c26b55970c007b77c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
